gemini:
  clients:
    - id: "account-1"
      secure_1psid: "g.a000CwkPDZJ8qm9IesXNZagOiEzFf7lfo2Zc0cFNYsk819OgvIQDalXz1agmExM2pjuM8phdMgACgYKAeISARUSFQHGX2MiGz6b52VB_BdEuMUg-tGKphoVAUF8yKq2ZuQfhRBlkGGi9GzvdygF0076"
      secure_1psidts: "sidts-CjIBkldj_yCQn9LzPiHAHVsqyA4ot9w1Izs-9pnpMsjkpVTACqHTuWYC80YuO6_cFp0VQhAA"
      proxy: null

  timeout: 600
  watchdog_timeout: 300
  auto_refresh: true
  refresh_interval: 600
  verbose: false
  max_chars_per_request: 1000000
  oversized_context_strategy: "compaction"
  chat_mode: "normal"
  model_strategy: "append"
  models: []